version: '2'

services:
  backend:
    image: 'book-store-backend:latest'
    build:
      context: .
    container_name: backend
    ports:
      - "9595:9595"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/book_store
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=newPassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'book-store-db:latest'
    build:
      context: Librarian/db/.
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=newPassword
      - POSTGRES_DB=book_store
    ports:
      - "5432:5432"

  ui:
    image: 'book-store-ui:latest'
    build:
      context: Librarian/frontend/lab2-librarian/.
    container_name: ui
    depends_on:
      - backend
    ports:
      - "3000:3000"
